[project]
name = "swm-clickhouse"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "clickhouse-connect>=0.8.15",
  "pyarrow>=20.0.0",
  "swm-common",
  "swm-models"
]

[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/swm_clickhouse"]
