[project]
name = "ingestion-api"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "fastapi>=0.115.12",
  "uvicorn[standard]>=0.34.2",
  "swm-common",
  "swm-auth",
  "swm-schemas",
  "swm-redis"
]

[project.scripts]
ingestion-api = "ingestion_api.main:run"

[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ingestion_api"]
