[project]
name = "admin-api"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "fastapi>=0.115.12",
  "python-multipart>=0.0.9",
  "uvicorn[standard]>=0.34.2",
  "clickhouse-connect>=0.8.15",
  "openpyxl>=3.1.5",
  "reportlab>=4.2.2",
  "swm-common",
  "swm-auth",
  "swm-db",
  "swm-redis"
]

[project.scripts]
admin-api = "admin_api.main:run"

[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/admin_api"]
